In [2]:
import numpy as np
import os

In [3]:
os.chdir('/home/mai/notebooks/final_thesis/')

In [4]:

# Load the array
node_ts = np.load('./datasets/DGraphFin2/dgraphfinv2_node_timestamp.npy')

# Inspect the data
print(f"Shape: {node_ts.shape}")
print(f"Data Type: {node_ts.dtype}")
print(node_ts[:5]) # View the first 5 rows

Shape: (3700550,)
Data Type: int32
[-2147483648 -2147483648 -2147483648 -2147483648 -2147483648]


In [5]:
node_ts.min(), node_ts.max()

node_ts[node_ts < 0].max()

np.int32(-2147483648)

In [6]:
data = np.load('./datasets/DGraphFin/dgraphfin.npz')

data['x'].shape, data['y'].shape

((3700550, 17), (3700550,))

In [7]:
np.where(data['y'] == 1)[0][:10]

array([1343, 1605, 1744, 2436, 2515, 2535, 3338, 3376, 3445, 3484])

In [8]:
node_ts[np.where(data['y'] == 1)[0][:10]]

array([  0,   0,   0,   0,   0, 257, 291,   0,   0,   0], dtype=int32)

In [9]:
# Load the array
edge_ts = np.load('./datasets/DGraphFin2/dgraphfinv2_edge_timestamp.npy')

# Inspect the data
print(f"Shape: {edge_ts.shape}")
print(f"Data Type: {edge_ts.dtype}")
print(edge_ts[:5]) # View the first 5 rows

Shape: (4300999,)
Data Type: int32
[223 235 209 443   0]


In [10]:
data['edge_timestamp'][:5]

array([254, 266, 240, 474,   7])

In [16]:
data['train_mask'].shape[0] + data['valid_mask'].shape[0] + data['test_mask'].shape[0]

1225601