In [1]:
import numpy as np

# Load the array
data = np.load('./datasets/DGraphFin/dgraphfinv2_node_timestamp.npy')

# Inspect the data
print(f"Shape: {data.shape}")
print(f"Data Type: {data.dtype}")
print(data[:5]) # View the first 5 rows

Shape: (3700550,)
Data Type: int32
[-2147483648 -2147483648 -2147483648 -2147483648 -2147483648]


In [2]:
data.min(), data.max()

(np.int32(-2147483648), np.int32(793))

In [3]:
# Load the array
data = np.load('./datasets/DGraphFin/dgraphfinv2_edge_timestamp.npy')

# Inspect the data
print(f"Shape: {data.shape}")
print(f"Data Type: {data.dtype}")
print(data[:5]) # View the first 5 rows

Shape: (4300999,)
Data Type: int32
[223 235 209 443   0]


In [4]:
# Load the archive
data = np.load('./datasets/DGraphFin/dgraphfin.npz')

# 1. See what arrays (keys) are inside
print("Keys available:", data.files)

data['x'].shape, data['y'].shape

Keys available: ['x', 'y', 'edge_index', 'edge_type', 'edge_timestamp', 'train_mask', 'valid_mask', 'test_mask']


((3700550, 17), (3700550,))

In [5]:
data['edge_type'].shape

(4300999,)

In [6]:
data['edge_type'].min(), data['edge_type'].max()

(np.int64(1), np.int64(11))

In [7]:
data['edge_timestamp'].shape

(4300999,)

In [8]:
data['edge_timestamp'].min(), data['edge_timestamp'].max()

(np.int64(1), np.int64(821))

In [9]:
data['x'][0]

array([ 0.,  5., -1., -1., -1., -1., -1., -1., -1., -1.,  0., -1., -1.,
       -1., -1., -1., -1.])

In [10]:
data['train_mask']

array([2735458, 3025736, 2659385, ...,  572867, 3250251, 1337270],
      shape=(857899,))

In [11]:
data['edge_index']

array([[ 476699, 2915516],
       [ 347800, 1271242],
       [ 154317, 2104635],
       ...,
       [1894383, 1147595],
       [1895741, 1314434],
       [1206795, 2072636]], shape=(4300999, 2))