In [1]:
import numpy as np
import os

In [2]:
os.chdir('/home/mai/notebooks/final_thesis/')

In [3]:

# Load the array
node_ts = np.load('./datasets/DGraphFin2/dgraphfinv2_node_timestamp.npy')
data = np.load('./datasets/DGraphFin/dgraphfin.npz')
edge_ts = np.load('./datasets/DGraphFin2/dgraphfinv2_edge_timestamp.npy')


In [4]:
node_ts.min(), node_ts.max()

# node_ts[node_ts < 0].max(), node_ts[node_ts>=0].min()

(np.int32(-2147483648), np.int32(793))

In [13]:
node_ts[node_ts > 0][:5]

array([257, 291, 121, 195, 265], dtype=int32)

In [47]:
node_ids = np.where(node_ts > 0)[0][:10]
mask = np.isin(data['edge_index'][:, 1], node_ids)
e_idx = data['edge_index'][mask]
edge_ids = np.where(mask)[0]

In [48]:
node_ids

array([2535, 3338, 3602, 4806, 4969, 5836, 5898, 6062, 6528, 7186])

In [49]:
data['edge_timestamp'][edge_ids]

array([490, 225, 402, 227, 549,  49, 498])

In [50]:
e_idx

array([[3304012,    7186],
       [1959079,    3338],
       [1485257,    2535],
       [ 438749,    3338],
       [  67603,    3602],
       [ 536205,    4806],
       [1433209,    4969]])

In [51]:
node_ts[7186]

np.int32(237)

In [52]:
train_mask = data['train_mask']

node_ts[train_mask]

array([        249,         609,         290, ..., -2147483648,
       -2147483648, -2147483648], shape=(857899,), dtype=int32)

In [55]:
data.keys

<bound method NpzFile.keys of NpzFile './datasets/DGraphFin/dgraphfin.npz' with keys: x, y, edge_index, edge_type, edge_timestamp...>